name: Cleanup

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          rm -rf node_modules
          rm -rf dist
          npm install
