name: Manual Workflow Dispatch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the Workflow
        uses: ad-m/github-push-action@master
        with:
          branch: main
